language: r

cache: packages

sudo: required

apt_packages:
  - libudunits2-dev

r_github_packages:
  - jimhester/covr
  - edzer/units

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
  slack:
    secure: YfoeIwy3fwgW8FeAC486T866tkF2GYGS/KtW25h0FL6VvYTC6LGcTTdDg2gxzP2r4uginbqgXJ/Id8fMqu2llXG/ZEtPMyfOhtTc7eDkKh9+wVjB98iI9FCiJ4SjvW3woDdSIDur1bal0g1464h3pTTI8aPKLZnCYnlbwA3NEylaTxnMJEc/1ltsOx9FfPfJRcIk2ETLtzDI+Al7s9Tt7H3g3uIyGos8ZtsJtgfKD6ae1Nn2W+p+N8peex88x+ntugyh8Sl7Lu/3/Ecv4XUGgGOKuv0HF+RcQQ3/HeFYCF5VPzNSjOioss25E7jz348iNxEtdr+TVSRDJ/JMo9hsmPwtbS4CGy/KMwy+7jyJDRJal+1S8bqBCbsXqjUQEytthYcgWA4TmtxiKGEkiqpbKHTBkxmKQlY5dJD47ISEXCUc1WuOS5CpCNeo45eXgJEsKOMrMLGFhn2GF1an+byOT3Nrh7/8EK91b7ml/6Oy3e2hpI98M4Ftq8gvJ64nJs1oLv/XqG/TmOpUVT6N8SB85wYEqTKVFCYQyW/PTdz5YrAeR7yL6s32CuyycERSHpqU0niBRWGwQnjVFgITowKiw9l4gQWLwXM30Ez1/JwKWQ5rz6pNl1LP0xWEESyiuhxUtIVYp1eWk9knhSQonWwVLFSZu6+AZSFGRMlpHSrGE0M=
    on_success: always
    on_failure: always
